### ISSUE TITLE
Not compatible with your operating system or architecture

### ISSUE THREAD

**Issue by creaux** [oren/docker-nativescript#6]
```
npm ERR! Linux 4.9.60-linuxkit-aufs
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "nativescript" "-g" "--unsafe-perm"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code EBADPLATFORM

npm ERR! notsup Unsupported
npm ERR! notsup Not compatible with your operating system or architecture: fsevents@1.1.2
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: x64

> nativescript@3.4.2 preuninstall /usr/local/lib/node_modules/nativescript
> node preuninstall.js

/usr/local/lib/node_modules/nativescript/lib/common/scripts/node-args.js:3
const getNodeArgs = () => {
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/nativescript/preuninstall.js:6:16)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
npm WARN continuing anyway nativescript@3.4.2 preuninstall: `node preuninstall.js`
npm WARN continuing anyway Exit status 1

npm ERR! Please include the following file with any support request:
npm ERR!     /src/npm-debug.log
The command '/bin/sh -c npm install nativescript -g --unsafe-perm' returned a non-zero code: 1
```

**Comment by xerxicodex** [comment]
+1 same issue
